export enum CHORD_LETTER {
  C = "C",
  Db = "Db",
  D = "D",
  Eb = "Eb",
  E = "E",
  F = "F",
  FS = "F#",
  G = "G",
  Ab = "Ab",
  A = "A",
  Bb = "Bb",
  B = "B",
}

export enum CHORD_QUALITY {
  MAJOR = "MAJOR",
  MINOR = "MINOR",
  DIMINISHED = "DIMINISHED",
}

export enum CHORD_TYPE {
  C_MAJOR = "C MAJOR",
  C_MINOR = "C MINOR",
  C_DIMINISHED = "C DIMINISHED",

  D_FLAT_MAJOR = "Db MAJOR",
  D_FLAT_MINOR = "Db MINOR",
  D_FLAT_DIMINISHED = "Db DIMINISHED",

  D_MAJOR = "D MAJOR",
  D_MINOR = "D MINOR",
  D_DIMINISHED = "D DIMINISHED",

  E_FLAT_MAJOR = "Eb MAJOR",
  E_FLAT_MINOR = "Eb MINOR",
  E_FLAT_DIMINISHED = "Eb DIMINISHED",

  E_MAJOR = "E MAJOR",
  E_MINOR = "E MINOR",
  E_DIMINISHED = "E DIMINISHED",

  F_MAJOR = "F MAJOR",
  F_MINOR = "F MINOR",
  F_DIMINISHED = "F DIMINISHED",

  F_SHARP_MAJOR = "F# MAJOR",
  F_SHARP_MINOR = "F# MINOR",
  F_SHARP_DIMINISHED = "F# DIMINISHED",

  G_MAJOR = "G MAJOR",
  G_MINOR = "G MINOR",
  G_DIMINISHED = "G DIMINISHED",

  A_FLAT_MAJOR = "Ab MAJOR",
  A_FLAT_MINOR = "Ab MINOR",
  A_FLAT_DIMINISHED = "Ab DIMINISHED",
  
  A_MINOR = "A MINOR",
  A_MAJOR = "A MAJOR",
  A_DIMINISHED = "A DIMINISHED",

  B_FLAT_MAJOR = "Bb MAJOR",
  B_FLAT_MINOR = "Bb MINOR",
  B_FLAT_DIMINISHED = "Bb DIMINISHED",

  B_MINOR = "B MINOR",
  B_MAJOR = "B MAJOR",
  B_DIMINISHED = "B DIMINISHED",
}

export const CHORD_LETTER_TO_TYPE: Record<CHORD_QUALITY, Record<CHORD_LETTER, CHORD_TYPE>> = {
  [CHORD_QUALITY.MAJOR]: {
    [CHORD_LETTER.C]: CHORD_TYPE.C_MAJOR,
    [CHORD_LETTER.Db]: CHORD_TYPE.D_FLAT_MAJOR,
    [CHORD_LETTER.D]: CHORD_TYPE.D_MAJOR,
    [CHORD_LETTER.Eb]: CHORD_TYPE.E_FLAT_MAJOR,
    [CHORD_LETTER.E]: CHORD_TYPE.E_MAJOR,
    [CHORD_LETTER.F]: CHORD_TYPE.F_MAJOR,
    [CHORD_LETTER.FS]: CHORD_TYPE.F_SHARP_MAJOR,
    [CHORD_LETTER.G]: CHORD_TYPE.G_MAJOR,
    [CHORD_LETTER.Ab]: CHORD_TYPE.A_FLAT_MAJOR,
    [CHORD_LETTER.A]: CHORD_TYPE.A_MAJOR,
    [CHORD_LETTER.Bb]: CHORD_TYPE.B_FLAT_MAJOR,
    [CHORD_LETTER.B]: CHORD_TYPE.B_MAJOR,
  },
  [CHORD_QUALITY.MINOR]: { 
    [CHORD_LETTER.C]: CHORD_TYPE.C_MINOR,
    [CHORD_LETTER.Db]: CHORD_TYPE.D_FLAT_MINOR,
    [CHORD_LETTER.D]: CHORD_TYPE.D_MINOR,
    [CHORD_LETTER.Eb]: CHORD_TYPE.E_FLAT_MINOR,
    [CHORD_LETTER.E]: CHORD_TYPE.E_MINOR,
    [CHORD_LETTER.F]: CHORD_TYPE.F_MINOR,
    [CHORD_LETTER.FS]: CHORD_TYPE.F_SHARP_MINOR,
    [CHORD_LETTER.G]: CHORD_TYPE.G_MINOR,
    [CHORD_LETTER.Ab]: CHORD_TYPE.A_FLAT_MINOR,
    [CHORD_LETTER.A]: CHORD_TYPE.A_MINOR,
    [CHORD_LETTER.Bb]: CHORD_TYPE.B_FLAT_MINOR,
    [CHORD_LETTER.B]: CHORD_TYPE.B_MINOR,
   },
  [CHORD_QUALITY.DIMINISHED]: {
    [CHORD_LETTER.C]: CHORD_TYPE.C_DIMINISHED,
    [CHORD_LETTER.Db]: CHORD_TYPE.D_FLAT_DIMINISHED,
    [CHORD_LETTER.D]: CHORD_TYPE.D_DIMINISHED,
    [CHORD_LETTER.Eb]: CHORD_TYPE.E_FLAT_DIMINISHED,
    [CHORD_LETTER.E]: CHORD_TYPE.E_DIMINISHED,
    [CHORD_LETTER.F]: CHORD_TYPE.F_DIMINISHED,
    [CHORD_LETTER.FS]: CHORD_TYPE.F_SHARP_MINOR,
    [CHORD_LETTER.G]: CHORD_TYPE.G_MINOR,
    [CHORD_LETTER.Ab]: CHORD_TYPE.A_FLAT_MINOR,
    [CHORD_LETTER.A]: CHORD_TYPE.A_MINOR,
    [CHORD_LETTER.Bb]: CHORD_TYPE.B_FLAT_MINOR,
    [CHORD_LETTER.B]: CHORD_TYPE.B_MINOR,
  },
};

export function getChordType(
  letter: CHORD_LETTER,
  quality: CHORD_QUALITY = CHORD_QUALITY.MAJOR
): CHORD_TYPE {
  return CHORD_LETTER_TO_TYPE[quality][letter];
}

export const FREQS: Record<string, number> = {
  // Octave 2
  C2: 65.41,
  CS2: 69.30,
  D2: 73.42,
  DS2: 77.78,
  E2: 82.41,
  F2: 87.31,
  FS2: 92.50,
  G2: 98.00,
  GS2: 103.83,
  A2: 110.00,
  AS2: 116.54,
  B2: 123.47,
  // Octave 3
  C3: 130.81,
  CS3: 138.59,
  D3: 146.83,
  DS3: 155.56,
  E3: 164.81,
  F3: 174.61,
  FS3: 185.00,
  G3: 196.00,
  GS3: 207.65,
  A3: 220.00,
  AS3: 233.08,
  B3: 246.94,
  // Octave 4
  C4: 261.63,
  CS4: 277.18,
  D4: 293.66,
  DS4: 311.13,
  E4: 329.63,
  F4: 349.23,
  FS4: 369.99,
  G4: 392.0,
  GS4: 415.30,
  A4: 440.0,
  AS4: 466.16,
  B4: 493.88,
  // Octave 5
  C5: 523.25,
  CS5: 554.37,
  D5: 587.33,
  DS5: 622.25,
  E5: 659.26,
  F5: 698.46,
  FS5: 739.99,
  G5: 783.99,
  GS5: 830.61,
  A5: 880.0,
  AS5: 932.33,
  B5: 987.77,
  // Octave 6
  C6: 1046.50,
  CS6: 1108.73,
  D6: 1174.66,
  DS6: 1244.51,
  E6: 1318.51,
  F6: 1396.91,
  FS6: 1479.98,
  G6: 1567.98,
  GS6: 1661.22,
  A6: 1760.00,
  AS6: 1864.66,
  B6: 1975.53,
  // Octave 7
  C7: 2093.00,
  CS7: 2217.46,
  D7: 2349.32,
  DS7: 2489.02,
  E7: 2637.02,
  F7: 2793.83,
  FS7: 2959.96,
  G7: 3135.96,
  GS7: 3322.44,
  A7: 3520.00,
  AS7: 3729.31,
  B7: 3951.07,
};

export const CHORDS = {
  [CHORD_TYPE.C_MAJOR]:      [FREQS.C4, FREQS.E4, FREQS.G4],
  [CHORD_TYPE.C_MINOR]:      [FREQS.C4, FREQS.DS4, FREQS.G4],
  [CHORD_TYPE.C_DIMINISHED]: [FREQS.C4, FREQS.DS4, FREQS.FS4],
  [CHORD_TYPE.D_FLAT_MAJOR]: [FREQS.CS4, FREQS.F4, FREQS.GS4],
  [CHORD_TYPE.D_FLAT_MINOR]: [FREQS.CS4, FREQS.E4, FREQS.GS4],
  [CHORD_TYPE.D_FLAT_DIMINISHED]: [FREQS.CS4, FREQS.E4, FREQS.G4],
  [CHORD_TYPE.D_MAJOR]:      [FREQS.D4, FREQS.FS4, FREQS.A4],
  [CHORD_TYPE.D_MINOR]:      [FREQS.D4, FREQS.F4, FREQS.A4],
  [CHORD_TYPE.D_DIMINISHED]: [FREQS.D4, FREQS.F4, FREQS.GS4],
  [CHORD_TYPE.E_FLAT_MAJOR]: [FREQS.DS4, FREQS.G4, FREQS.AS4],
  [CHORD_TYPE.E_FLAT_MINOR]: [FREQS.DS4, FREQS.FS4, FREQS.AS4],
  [CHORD_TYPE.E_FLAT_DIMINISHED]: [FREQS.DS4, FREQS.FS4, FREQS.A4],
  [CHORD_TYPE.E_MAJOR]:      [FREQS.E4, FREQS.GS4, FREQS.B4],
  [CHORD_TYPE.E_MINOR]:      [FREQS.E4, FREQS.G4, FREQS.B4],
  [CHORD_TYPE.E_DIMINISHED]: [FREQS.E4, FREQS.G4, FREQS.AS4],
  [CHORD_TYPE.F_MAJOR]:      [FREQS.F4, FREQS.A4, FREQS.C4],
  [CHORD_TYPE.F_MINOR]:      [FREQS.F4, FREQS.GS4, FREQS.C4],
  [CHORD_TYPE.F_DIMINISHED]: [FREQS.F4, FREQS.GS4, FREQS.B4],
  [CHORD_TYPE.F_SHARP_MAJOR]: [FREQS.FS4, FREQS.AS4, FREQS.CS4],
  [CHORD_TYPE.F_SHARP_MINOR]: [FREQS.FS4, FREQS.A4, FREQS.CS4],
  [CHORD_TYPE.F_SHARP_DIMINISHED]: [FREQS.FS4, FREQS.A4, FREQS.C4],
  [CHORD_TYPE.G_MAJOR]:      [FREQS.G4, FREQS.B4, FREQS.D4],
  [CHORD_TYPE.G_MINOR]:      [FREQS.G4, FREQS.AS4, FREQS.D4],
  [CHORD_TYPE.G_DIMINISHED]: [FREQS.G4, FREQS.AS4, FREQS.CS4],
  [CHORD_TYPE.A_FLAT_MAJOR]: [FREQS.GS4, FREQS.C5, FREQS.DS4],
  [CHORD_TYPE.A_FLAT_MINOR]: [FREQS.GS4, FREQS.B4, FREQS.DS4],
  [CHORD_TYPE.A_FLAT_DIMINISHED]: [FREQS.GS4, FREQS.B4, FREQS.D4],
  [CHORD_TYPE.A_MAJOR]:      [FREQS.A4, FREQS.CS4, FREQS.E4],
  [CHORD_TYPE.A_MINOR]:      [FREQS.A4, FREQS.C4, FREQS.E4],
  [CHORD_TYPE.A_DIMINISHED]: [FREQS.A4, FREQS.C4, FREQS.DS4],
  [CHORD_TYPE.B_FLAT_MAJOR]: [FREQS.AS4, FREQS.D4, FREQS.F4],
  [CHORD_TYPE.B_FLAT_MINOR]: [FREQS.AS4, FREQS.CS4, FREQS.F4],
  [CHORD_TYPE.B_FLAT_DIMINISHED]: [FREQS.AS4, FREQS.CS4, FREQS.E4],
  [CHORD_TYPE.B_MAJOR]:      [FREQS.B4, FREQS.DS4, FREQS.FS4],
  [CHORD_TYPE.B_MINOR]:      [FREQS.B4, FREQS.D4, FREQS.FS4],
  [CHORD_TYPE.B_DIMINISHED]: [FREQS.B4, FREQS.D4, FREQS.F4],
};

export const ARPEGGIOS: Record<CHORD_TYPE, number[]> = {
  [CHORD_TYPE.C_MAJOR]: [FREQS.C3, FREQS.E3, FREQS.G3, FREQS.C4, FREQS.E4, FREQS.G4, FREQS.C5, FREQS.E5, FREQS.G5, FREQS.C6, FREQS.E6, FREQS.G6],
  [CHORD_TYPE.C_MINOR]: [FREQS.C3, FREQS.DS3, FREQS.G3, FREQS.C4, FREQS.DS4, FREQS.G4, FREQS.C5, FREQS.DS5, FREQS.G5, FREQS.C6, FREQS.DS6, FREQS.G6],
  [CHORD_TYPE.C_DIMINISHED]: [FREQS.C3, FREQS.DS3, FREQS.FS3, FREQS.C4, FREQS.DS4, FREQS.FS4, FREQS.C5, FREQS.DS5, FREQS.FS5, FREQS.C6, FREQS.DS6, FREQS.FS6],

  [CHORD_TYPE.D_FLAT_MAJOR]: [FREQS.CS3, FREQS.F3, FREQS.GS3, FREQS.CS4, FREQS.F4, FREQS.GS4, FREQS.CS5, FREQS.F5, FREQS.GS5, FREQS.CS6, FREQS.F6, FREQS.GS6],
  [CHORD_TYPE.D_FLAT_MINOR]: [FREQS.CS3, FREQS.E3, FREQS.GS3, FREQS.CS4, FREQS.E4, FREQS.GS4, FREQS.CS5, FREQS.E5, FREQS.GS5, FREQS.CS6, FREQS.E6, FREQS.GS6],
  [CHORD_TYPE.D_FLAT_DIMINISHED]: [FREQS.CS3, FREQS.E3, FREQS.G3, FREQS.CS4, FREQS.E4, FREQS.G4, FREQS.CS5, FREQS.E5, FREQS.G5, FREQS.CS6, FREQS.E6, FREQS.G6],

  [CHORD_TYPE.D_MAJOR]: [FREQS.D3, FREQS.FS3, FREQS.A3, FREQS.D4, FREQS.FS4, FREQS.A4, FREQS.D5, FREQS.FS5, FREQS.A5, FREQS.D6, FREQS.FS6, FREQS.A6],
  [CHORD_TYPE.D_MINOR]: [FREQS.D3, FREQS.F3, FREQS.A3, FREQS.D4, FREQS.F4, FREQS.A4, FREQS.D5, FREQS.F5, FREQS.A5, FREQS.D6, FREQS.F6, FREQS.A6],
  [CHORD_TYPE.D_DIMINISHED]: [FREQS.D3, FREQS.F3, FREQS.GS3, FREQS.D4, FREQS.F4, FREQS.GS4, FREQS.D5, FREQS.F5, FREQS.GS5, FREQS.D6, FREQS.F6, FREQS.GS6],

  [CHORD_TYPE.E_FLAT_MAJOR]: [FREQS.DS3, FREQS.G3, FREQS.AS3, FREQS.DS4, FREQS.G4, FREQS.AS4, FREQS.DS5, FREQS.G5, FREQS.AS5, FREQS.DS6, FREQS.G6, FREQS.AS6],
  [CHORD_TYPE.E_FLAT_MINOR]: [FREQS.DS3, FREQS.FS3, FREQS.AS3, FREQS.DS4, FREQS.FS4, FREQS.AS4, FREQS.DS5, FREQS.FS5, FREQS.AS5, FREQS.DS6, FREQS.FS6, FREQS.AS6],
  [CHORD_TYPE.E_FLAT_DIMINISHED]: [FREQS.DS3, FREQS.FS3, FREQS.A3, FREQS.DS4, FREQS.FS4, FREQS.A4, FREQS.DS5, FREQS.FS5, FREQS.A5, FREQS.DS6, FREQS.FS6, FREQS.A6],

  [CHORD_TYPE.E_MAJOR]: [FREQS.E3, FREQS.GS3, FREQS.B3, FREQS.E4, FREQS.GS4, FREQS.B4, FREQS.E5, FREQS.GS5, FREQS.B5, FREQS.E6, FREQS.GS6, FREQS.B6],
  [CHORD_TYPE.E_MINOR]: [FREQS.E3, FREQS.G3, FREQS.B3, FREQS.E4, FREQS.G4, FREQS.B4, FREQS.E5, FREQS.G5, FREQS.B5, FREQS.E6, FREQS.G6, FREQS.B6],
  [CHORD_TYPE.E_DIMINISHED]: [FREQS.E3, FREQS.G3, FREQS.AS3, FREQS.E4, FREQS.G4, FREQS.AS4, FREQS.E5, FREQS.G5, FREQS.AS5, FREQS.E6, FREQS.G6, FREQS.AS6],

  [CHORD_TYPE.F_MAJOR]: [FREQS.F3, FREQS.A3, FREQS.C4, FREQS.F4, FREQS.A4, FREQS.C5, FREQS.F5, FREQS.A5, FREQS.C6, FREQS.F6, FREQS.A6, FREQS.C7],
  [CHORD_TYPE.F_MINOR]: [FREQS.F3, FREQS.GS3, FREQS.C4, FREQS.F4, FREQS.GS4, FREQS.C5, FREQS.F5, FREQS.GS5, FREQS.C6, FREQS.F6, FREQS.GS6, FREQS.C7],
  [CHORD_TYPE.F_DIMINISHED]: [FREQS.F3, FREQS.GS3, FREQS.B3, FREQS.F4, FREQS.GS4, FREQS.B4, FREQS.F5, FREQS.GS5, FREQS.B5, FREQS.F6, FREQS.GS6, FREQS.B6],

  [CHORD_TYPE.F_SHARP_MAJOR]: [FREQS.FS3, FREQS.AS3, FREQS.CS4, FREQS.FS4, FREQS.AS4, FREQS.CS5, FREQS.FS5, FREQS.AS5, FREQS.CS6, FREQS.FS6, FREQS.AS6, FREQS.CS7],
  [CHORD_TYPE.F_SHARP_MINOR]: [FREQS.FS3, FREQS.A3, FREQS.CS4, FREQS.FS4, FREQS.A4, FREQS.CS5, FREQS.FS5, FREQS.A5, FREQS.CS6, FREQS.FS6, FREQS.A6, FREQS.CS7],
  [CHORD_TYPE.F_SHARP_DIMINISHED]: [FREQS.FS3, FREQS.A3, FREQS.C4, FREQS.FS4, FREQS.A4, FREQS.C5, FREQS.FS5, FREQS.A5, FREQS.C6, FREQS.FS6, FREQS.A6, FREQS.C7],

  [CHORD_TYPE.G_MAJOR]: [FREQS.G3, FREQS.B3, FREQS.D4, FREQS.G4, FREQS.B4, FREQS.D5, FREQS.G5, FREQS.B5, FREQS.D6, FREQS.G6, FREQS.B6, FREQS.D7],
  [CHORD_TYPE.G_MINOR]: [FREQS.G3, FREQS.AS3, FREQS.D4, FREQS.G4, FREQS.AS4, FREQS.D5, FREQS.G5, FREQS.AS5, FREQS.D6, FREQS.G6, FREQS.AS6, FREQS.D7],
  [CHORD_TYPE.G_DIMINISHED]: [FREQS.G3, FREQS.AS3, FREQS.CS4, FREQS.G4, FREQS.AS4, FREQS.CS5, FREQS.G5, FREQS.AS5, FREQS.CS6, FREQS.G6, FREQS.AS6, FREQS.CS7],

  [CHORD_TYPE.A_FLAT_MAJOR]: [FREQS.GS3, FREQS.C4, FREQS.DS4, FREQS.GS4, FREQS.C5, FREQS.DS5, FREQS.GS5, FREQS.C6, FREQS.DS6, FREQS.GS6, FREQS.C7, FREQS.DS7],
  [CHORD_TYPE.A_FLAT_MINOR]: [FREQS.GS3, FREQS.B3, FREQS.DS4, FREQS.GS4, FREQS.B4, FREQS.DS5, FREQS.GS5, FREQS.B5, FREQS.DS6, FREQS.GS6, FREQS.B6, FREQS.DS7],
  [CHORD_TYPE.A_FLAT_DIMINISHED]: [FREQS.GS3, FREQS.B3, FREQS.D4, FREQS.GS4, FREQS.B4, FREQS.D5, FREQS.GS5, FREQS.B5, FREQS.D6, FREQS.GS6, FREQS.B6, FREQS.D7],

  [CHORD_TYPE.A_MAJOR]: [FREQS.A3, FREQS.CS4, FREQS.E4, FREQS.A4, FREQS.CS5, FREQS.E5, FREQS.A5, FREQS.CS6, FREQS.E6, FREQS.A6, FREQS.CS7, FREQS.E7],
  [CHORD_TYPE.A_MINOR]: [FREQS.A3, FREQS.C4, FREQS.E4, FREQS.A4, FREQS.C5, FREQS.E5, FREQS.A5, FREQS.C6, FREQS.E6, FREQS.A6, FREQS.C7, FREQS.E7],
  [CHORD_TYPE.A_DIMINISHED]: [FREQS.A3, FREQS.C4, FREQS.DS4, FREQS.A4, FREQS.C5, FREQS.DS5, FREQS.A5, FREQS.C6, FREQS.DS6, FREQS.A6, FREQS.C7, FREQS.DS7],

  [CHORD_TYPE.B_FLAT_MAJOR]: [FREQS.AS3, FREQS.D4, FREQS.F4, FREQS.AS4, FREQS.D5, FREQS.F5, FREQS.AS5, FREQS.D6, FREQS.F6, FREQS.AS6, FREQS.D7, FREQS.F7],
  [CHORD_TYPE.B_FLAT_MINOR]: [FREQS.AS3, FREQS.CS4, FREQS.F4, FREQS.AS4, FREQS.CS5, FREQS.F5, FREQS.AS5, FREQS.CS6, FREQS.F6, FREQS.AS6, FREQS.CS7, FREQS.F7],
  [CHORD_TYPE.B_FLAT_DIMINISHED]: [FREQS.AS3, FREQS.CS4, FREQS.E4, FREQS.AS4, FREQS.CS5, FREQS.E5, FREQS.AS5, FREQS.CS6, FREQS.E6, FREQS.AS6, FREQS.CS7, FREQS.E7],

  [CHORD_TYPE.B_MAJOR]: [FREQS.B3, FREQS.DS4, FREQS.FS4, FREQS.B4, FREQS.DS5, FREQS.FS5, FREQS.B5, FREQS.DS6, FREQS.FS6, FREQS.B6, FREQS.DS7, FREQS.FS7],
  [CHORD_TYPE.B_MINOR]: [FREQS.B3, FREQS.D4, FREQS.FS4, FREQS.B4, FREQS.D5, FREQS.FS5, FREQS.B5, FREQS.D6, FREQS.FS6, FREQS.B6, FREQS.D7, FREQS.FS7],
  [CHORD_TYPE.B_DIMINISHED]: [FREQS.B3, FREQS.D4, FREQS.F4, FREQS.B4, FREQS.D5, FREQS.F5, FREQS.B5, FREQS.D6, FREQS.F6, FREQS.B6, FREQS.D7, FREQS.F7],
};

export const CHORD_LETTER_ORDER = [
  CHORD_LETTER.Db, 
  CHORD_LETTER.Ab, 
  CHORD_LETTER.Eb, 
  CHORD_LETTER.Bb, 
  CHORD_LETTER.F, 
  CHORD_LETTER.C, 
  CHORD_LETTER.G, 
  CHORD_LETTER.D, 
  CHORD_LETTER.A, 
  CHORD_LETTER.E, 
  CHORD_LETTER.B, 
  CHORD_LETTER.FS
];

export const CHORD_QUALITY_ORDER = [
  CHORD_QUALITY.MAJOR,
  CHORD_QUALITY.MINOR,
] as const;

export const CHORD_QUALITY_LABELS = {
  [CHORD_QUALITY.MAJOR]: "Major",
  [CHORD_QUALITY.MINOR]: "Minor",
} as const;

export const getChordKey = (pressedChords: CHORD_TYPE[]) => {
  return pressedChords.slice().sort().join("-");
}

export const CHORD_LOOKUP: Record<string, CHORD_TYPE> = {
  [getChordKey([CHORD_TYPE.C_MAJOR])]: CHORD_TYPE.C_MAJOR,
  [getChordKey([CHORD_TYPE.C_MINOR])]: CHORD_TYPE.C_MINOR,
  [getChordKey([CHORD_TYPE.C_MAJOR, CHORD_TYPE.C_MINOR])]: CHORD_TYPE.C_DIMINISHED,

  [getChordKey([CHORD_TYPE.D_FLAT_MAJOR])]: CHORD_TYPE.D_FLAT_MAJOR,
  [getChordKey([CHORD_TYPE.D_FLAT_MINOR])]: CHORD_TYPE.D_FLAT_MINOR,
  [getChordKey([CHORD_TYPE.D_FLAT_MAJOR, CHORD_TYPE.D_FLAT_MINOR])]: CHORD_TYPE.D_FLAT_DIMINISHED,

  [getChordKey([CHORD_TYPE.D_MAJOR])]: CHORD_TYPE.D_MAJOR,
  [getChordKey([CHORD_TYPE.D_MINOR])]: CHORD_TYPE.D_MINOR,
  [getChordKey([CHORD_TYPE.D_MAJOR, CHORD_TYPE.D_MINOR])]: CHORD_TYPE.D_DIMINISHED,

  [getChordKey([CHORD_TYPE.E_FLAT_MAJOR])]: CHORD_TYPE.E_FLAT_MAJOR,
  [getChordKey([CHORD_TYPE.E_FLAT_MINOR])]: CHORD_TYPE.E_FLAT_MINOR,
  [getChordKey([CHORD_TYPE.E_FLAT_MAJOR, CHORD_TYPE.E_FLAT_MINOR])]: CHORD_TYPE.E_FLAT_DIMINISHED,

  [getChordKey([CHORD_TYPE.E_MAJOR])]: CHORD_TYPE.E_MAJOR,
  [getChordKey([CHORD_TYPE.E_MINOR])]: CHORD_TYPE.E_MINOR,
  [getChordKey([CHORD_TYPE.E_MAJOR, CHORD_TYPE.E_MINOR])]: CHORD_TYPE.E_DIMINISHED,

  [getChordKey([CHORD_TYPE.F_MAJOR])]: CHORD_TYPE.F_MAJOR,
  [getChordKey([CHORD_TYPE.F_MINOR])]: CHORD_TYPE.F_MINOR,
  [getChordKey([CHORD_TYPE.F_MAJOR, CHORD_TYPE.F_MINOR])]: CHORD_TYPE.F_DIMINISHED,

  [getChordKey([CHORD_TYPE.F_SHARP_MAJOR])]: CHORD_TYPE.F_SHARP_MAJOR,
  [getChordKey([CHORD_TYPE.F_SHARP_MINOR])]: CHORD_TYPE.F_SHARP_MINOR,
  [getChordKey([CHORD_TYPE.F_SHARP_MAJOR, CHORD_TYPE.F_SHARP_MINOR])]: CHORD_TYPE.F_SHARP_DIMINISHED,

  [getChordKey([CHORD_TYPE.G_MAJOR])]: CHORD_TYPE.G_MAJOR,
  [getChordKey([CHORD_TYPE.G_MINOR])]: CHORD_TYPE.G_MINOR,
  [getChordKey([CHORD_TYPE.G_MAJOR, CHORD_TYPE.G_MINOR])]: CHORD_TYPE.G_DIMINISHED,

  [getChordKey([CHORD_TYPE.A_FLAT_MAJOR])]: CHORD_TYPE.A_FLAT_MAJOR,
  [getChordKey([CHORD_TYPE.A_FLAT_MINOR])]: CHORD_TYPE.A_FLAT_MINOR,
  [getChordKey([CHORD_TYPE.A_FLAT_MAJOR, CHORD_TYPE.A_FLAT_MINOR])]: CHORD_TYPE.A_FLAT_DIMINISHED,

  [getChordKey([CHORD_TYPE.A_MAJOR])]: CHORD_TYPE.A_MAJOR,
  [getChordKey([CHORD_TYPE.A_MINOR])]: CHORD_TYPE.A_MINOR,
  [getChordKey([CHORD_TYPE.A_MAJOR, CHORD_TYPE.A_MINOR])]: CHORD_TYPE.A_DIMINISHED,

  [getChordKey([CHORD_TYPE.B_FLAT_MAJOR])]: CHORD_TYPE.B_FLAT_MAJOR,
  [getChordKey([CHORD_TYPE.B_FLAT_MINOR])]: CHORD_TYPE.B_FLAT_MINOR,
  [getChordKey([CHORD_TYPE.B_FLAT_MAJOR, CHORD_TYPE.B_FLAT_MINOR])]: CHORD_TYPE.B_FLAT_DIMINISHED,


  [getChordKey([CHORD_TYPE.B_MAJOR])]: CHORD_TYPE.B_MAJOR,
  [getChordKey([CHORD_TYPE.B_MINOR])]: CHORD_TYPE.B_MINOR,
  [getChordKey([CHORD_TYPE.B_MAJOR, CHORD_TYPE.B_MINOR])]: CHORD_TYPE.B_DIMINISHED,
};