platform :ios, '15.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!

target 'OmnichordTemp' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end
end
